apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: smb-csi-driver-controller-pdb
  namespace: ${NAMESPACE}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: smb-csi-driver-controller
