kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: efs-node-privileged-binding
subjects:
  - kind: ServiceAccount
    name: aws-efs-csi-driver-node-sa
    namespace: ${NAMESPACE}
roleRef:
  kind: ClusterRole
  name: efs-privileged-role
  apiGroup: rbac.authorization.k8s.io
