apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ${ASSET_PREFIX}-node-monitor
  namespace: openshift-cluster-csi-drivers
spec:
  # Empty list to make json-patch work
  endpoints: []
  jobLabel: component
  selector:
    matchLabels:
      app: ${ASSET_PREFIX}-node-metrics
